#!/bin/bash
# sweep_gpu.sh — launcher: submits one SLURM job per (blocks, threads) config.
#
# NOT a SLURM job itself — run directly from the repo root:
#   bash scripts/sweep_gpu.sh
#
# Submits 35 independent jobs (7 block counts × 5 thread counts) to edu-short.
# Each job echoes the KERNEL: banner then runs spmv_gpu_stride, so that
# parse_results.py processes the output files exactly as for batch_gpu.sh.
#
# After all jobs finish:
#   uv run scripts/parse_results.py outputs/R-spmv_sweep_*.txt --out results_tables/sweep.csv
#   uv run scripts/plot_sweep.py results_tables/sweep.csv
# plot_sweep.py prints the best config; write it to assets/best_gpu_config.sh
# so that batch_gpu.sh picks it up automatically.
#
# NOTE (from_development_to_large_scale_matrices.md):
#   When large matrices are added, update SWEEP_MATRIX below to point to
#   a large structured/diagonal matrix (e.g. a FEM stiffness or circuit matrix
#   with 10M+ NNZ). With small matrices kernel launch overhead dominates and
#   configuration differences are barely measurable.

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

BIN="$REPO_DIR/bin/GPU/spmv_gpu_stride.exec"
if [ ! -f "$BIN" ]; then
    echo "[error] spmv_gpu_stride.exec not built — run: make gpu"
    exit 1
fi

# ── Sweep target matrix ───────────────────────────────────────────────────────
# bcsstk17: structured stiffness matrix, 428K NNZ — largest structured matrix
# in the current development dataset. Replace with a larger diagonal matrix
# once download_data.sh is extended (see from_development_to_large_scale_matrices.md).
SWEEP_MATRIX=$(find "$REPO_DIR/Data" -name "bcsstk17.mtx" | head -1)

if [ -z "$SWEEP_MATRIX" ]; then
    echo "[error] sweep matrix not found in Data/. Run scripts/download_data.sh first."
    exit 1
fi

MATRIX_NAME=$(basename "$SWEEP_MATRIX")

# ── Sweep ranges ──────────────────────────────────────────────────────────────
BLOCKS=(1 4 8 16 32 64 128)
THREADS=(32 128 256 512 1024)

echo "Sweep: spmv_gpu_stride on $MATRIX_NAME"
echo "Blocks:          ${BLOCKS[*]}"
echo "Threads/block:   ${THREADS[*]}"
echo "Total configs:   $((${#BLOCKS[@]} * ${#THREADS[@]}))"
echo ""

mkdir -p "$REPO_DIR/outputs"

for blocks in "${BLOCKS[@]}"; do
    for threads in "${THREADS[@]}"; do
        job_name="spmv_sweep_b${blocks}_t${threads}"

        JOB_SUBMISSION=$(sbatch \
            --partition=edu-short \
            --account=gpu.computing26 \
            --nodes=1 \
            --ntasks=1 \
            --cpus-per-task=1 \
            --gres=gpu:1 \
            --job-name="$job_name" \
            --output="$REPO_DIR/outputs/R-${job_name}.%j.txt" \
            --error="$REPO_DIR/outputs/R-${job_name}.%j.err" \
            --wrap="echo '========================================' && \
echo 'KERNEL: spmv_gpu_stride_b${blocks}_t${threads}  MATRIX: ${MATRIX_NAME}' && \
echo '========================================' && \
\"${BIN}\" \"${SWEEP_MATRIX}\" ${threads} ${blocks}")

        JOB_ID=$(echo "$JOB_SUBMISSION" | grep -oP 'Submitted batch job \K[0-9]+')
        echo "[submitted] blocks=$blocks threads=$threads  job_id=$JOB_ID"
    done
done

echo ""
echo "All $((${#BLOCKS[@]} * ${#THREADS[@]})) jobs submitted."
echo "When complete, run:"
echo "  uv run scripts/parse_results.py \"$REPO_DIR/outputs/R-spmv_sweep_*.txt\" --out results_tables/sweep.csv"
echo "  uv run scripts/plot_sweep.py results_tables/sweep.csv"
echo "Then write the printed best config to assets/best_gpu_config.sh:"
echo "  mkdir -p assets && printf '# Auto-generated by sweep_gpu.sh\nBEST_BLOCKS=<N>\nBEST_THREADS=<M>\n' > assets/best_gpu_config.sh"
